### ISSUE TITLE
[runwhen-local-feedback] adding Oracle Cloud OKE authentication

### ISSUE THREAD

**Issue by stebo85** [runwhen-contrib/runwhen-local#314]
**Observation** 
I would like to try runwhen-local on my OKE Kubernetes clusters on Oracle Cloud. Unfortunately the kubeconfig converter ./gen_rw_kubeconfig.sh doesn't handle the Oracle authentication. This is how my config file looks like:

```
apiVersion: v1
kind: ""
clusters:
- name: cluster-c6oz4zfbmka
  cluster:
    server: ****
    certificate-authority-data: ***
users:
- name: user-c6oz4zfbmka
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: oci
      args:
      - ce
      - cluster
      - generate-token
      - --cluster-id
      - ocid1.cluster.oc1.***
      - --region
      - ***
      - --profile
      - ***
      env: []
contexts:
- name: context-c6oz4zfbmka
  context:
    cluster: cluster-c6oz4zfbmka
    user: user-c6oz4zfbmka
current-context: context-c6oz4zfbmka
```

**Possible Suggestions**
It looks like GKE has a similar token based authentication and you already seem to handle this in the current gen_rw_kubeconfig.sh script:

```
cat <<E0F >gen_rw_kubeconfig.sh

#!/bin/bash

# Set the working directory
workdir="$workdir"

# Check if the workdir/shared folder exists
if [ -d "$workdir/shared" ]; then
  echo "Directory '$workdir/shared' exists."
else
  echo "Error: Directory '$workdir/shared' does not exist."
  exit 1
fi

# Copy ~/.kube/config to $shared_dir/kubeconfig
cp ~/.kube/config "$workdir/shared/kubeconfig"

# Find Kubernetes users using gke-gcloud-auth-plugin
users=\$(grep -B 7 "command: gke-gcloud-auth-plugin" "$workdir/shared/kubeconfig" | awk '/- name:/{print \$3}')

yq eval 'del(.users[].user.exec)' -i "$workdir/shared/kubeconfig"

# Perform substitution using yq
for user in \$users; do
        echo "Fetching new token"
	token=\$(gke-gcloud-auth-plugin generate-token "\$user" | awk -F'"' '/"token":/{print \$4}')
	T=\$token yq  eval '.users[].user |= {"token": env(T)}' -i "$workdir/shared/kubeconfig"
	#yq eval ".users[] | select(.name == \"\$user\") | .user.token = \"\$token\"" -i "$workdir/shared/kubeconfig"
done

# Set permissions for container to read the file
chmod 655 "$workdir/shared/kubeconfig" 

# Output the modified kubeconfig
cat "$workdir/shared/kubeconfig"
E0F
```

Would it be as simple as adding a similar line to google:
token=\$(gke-gcloud-auth-plugin generate-token "\$user" | awk -F'"' '/"token":/{print \$4}')

and use the oci command instead:
```
oci ce cluster generate-token --cluster-id ocid1.cluster.oc1.***--region ap-sydney-1 --profile myprofile
```

This OCI command results in:
```
{
    "apiVersion": "client.authentication.k8s.io/v1beta1",
    "kind": "ExecCredential",
    "status": {
        "token": "_TOKEN_",
        "expirationTimestamp": "2023-08-30T05:35:37.977978Z"
    }
}

**Any other details or context**
