### ISSUE TITLE
[runwhen-local-feedback] support OIDC kubelogin in gen_rw_kubeconfig.sh

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/runwhen-local#320]
**Observation** 
For users of kubelogin, we need to enhance gen_rw_kubeconfig.sh to support the token generation as we do for gke and oke. 

**Any other details or context**

Example exec stanza: 
```
users:
  - name: someuser
    user:
      exec:
        apiVersion: [client.authentication.k8s.io/v1beta1](http://client.authentication.k8s.io/v1beta1)
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://issuer.region.amazonaws.com/xxxxxxx
          - --oidc-client-id=xxxxxxx
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false

```

**Comment by stewartshea** [comment]
#323 solved for `kubectl oidc-login` but not for the `kubelogin` binary, for example; 

```
- name: clusterUser_Development_DevelopmentKubernetes
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - <REDACTED>
      - --client-id
      - <REDACTED>
      - --tenant-id
      - <REDACTED>
      - --login
      - devicecode
      command: kubelogin
      env: null
      installHint: |2

        kubelogin is not installed which is required to connect to AAD enabled cluster.

        To learn more, please go to https://aka.ms/aks/kubelogin
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
