### ISSUE TITLE
[runwhen-local-feedback] Bug - slx name (object name) is not unique enough and causes missed objects when duplicated 

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/runwhen-local#341]
**Observation** 
We have an environment where there are multiple objects with the same name. By example, it's called `frontend` and is of type `deployment`. It is a different object in multiple namespace, namely `online-boutique` and `monitoring`. The slx name that is generated in both cases is  `frontend-depl-health` - and so only on of these gets generated - or more likely they both get generated and the last one to write out it's config wins. 

We need to expand the `{{ slx_name }}` to support additional unique attributes, possibly such as namespace and cluster - as this example, across multiple clusters, would cause the same issue. 

The example match rule in the codebundle is this: 
```
apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/kubernetes/resources/labeled/deploy.svg
  alias: {{match_resource.resource.metadata.name}} Deployment Health
  asMeasuredBy: The count of unready pods managed as reported by deployment status. 
  configProvided:
  - name: OBJECT_NAME
    value: {{match_resource.resource.metadata.name}}
  owners:
  - {{workspace.owner_email}}
  statement: Pods for {{match_resource.resource.metadata.name}} deployments should be in a ready state. There should be Zero unready pods. 
  additionalContext:  
    namespace: "{{match_resource.resource.metadata.namespace}}"
    labelMap: "{{match_resource.resource.metadata.labels}}" 
```

I could try to update the name to add more details myself, but I suspect fixing up `{{ slx_name }` is a more sustainable strategy. 

**Possible Suggestions**
Expand SLX name to include additional unique components like namespace and cluster. 

**Any other details or context**
