### ISSUE TITLE
[runwhen-local-feedback] duplicate namespace or object names are not indexed/discovered across multiple clusters

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/runwhen-local#377]
**Observation** 
We've seen this in a couple of instances where somehow there is collision in that multiple resources of the same name, existing in different clusters, result in only one instance being discovered. For example, the namespace `flux-system` will only be indexed / rendered in one cluster even if it exists in three. 

Possibly related is an instance where we saw object names with many similar starting characters exhibit behaviour like this in the same cluster but with namespaces that started in a very similar way. Such as `ns00001` and `ns0002` - both had an s3-proxy object, but only one was discovered. 

**Possible Suggestions**

**Any other details or context**

**Comment by stewartshea** [comment]
We can see that the qualifiers are indeed being taken into account by looking at the singularly rendered instance:
```
apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: ws--flx-sys-cnt-cls-ns-health
  labels:
    slx: ws--flx-sys-cnt-cls-ns-health
    workspace: ws
  annotations:
    fullSlxName: flux-system-controlplane-cluster-ns-health
spec:
```
this is also confirmed by some of the debug output, so there's something else that seems to be causing the issue. I also added some debug lines to see if there was a path collision in the output items, but that turned up no results, indicating that the choice to "not render the output" for the remaining objects is occuring earlier in the process.
