### ISSUE TITLE
[runwhen-local-feedback] Command explanations and learning links are no longer available

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/runwhen-local#383]
**Observation** 
We've just added some additional context into the task names to improve search, but the second necessary tasks to tune up the metadata contents has not been completed. 

**Possible Suggestions**

**Any other details or context**

As a temporary workaround, the `workspaceInfo.yaml` file can point to an older tag, such as 
```
codeCollections:
  - repoURL: "https://github.com/runwhen-contrib/rw-public-codecollection.git"
    ref: main
    codeBundles: ["*"]
  - repoURL: "https://github.com/runwhen-contrib/rw-cli-codecollection.git"
    tag: v0.0.8
    codeBundles: [!*"]
```

https://docs.runwhen.com/public/v/runwhen-local/user-guide/user_guide-advanced_configuration
