### ISSUE TITLE
[runwhen-local-feedback] Test and document proxy configuration

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/runwhen-local#443]
**Observation** 
We aren't sure yet of the required settings or modifications required to use a proxy with RWL. 

**Possible Suggestions**
Set up a test proxy, test if passing standard environment variables are picked up automatically, or if code adjustments are required (the `requests` library may require update, `urllib` may not)

**Any other details or context**

**Comment by stewartshea** [comment]
This has been tested with a minimal setup running on Docker: 

Deploy a simple squid proxy server with no config (which will default deny): 
```
$ docker run --name squid-proxy --restart=always -d -p 3128:3128 sameersbn/squid:3.5.27-2
```

Run the docker image with the proxy variables:
```
# docker run --name RunWhenLocal --network host -p 8081:8081 -e NO_PROXY="localhost" -e HTTP_PROXY="http://localhost:3128" -e HTTPS_PROXY="http://localhost:3128" -v $workdir/shared:/shared -d runwhen-local:test
``` 

See deny in proxy: 
```
$ docker exec -it squid-proxy tail -f /var/log/squid/access.log
1708775728.980      0 192.168.41.138 TCP_DENIED/403 5688 GET http://844fbc21773c:3128/squid-internal
```

And error in RunWhen Local: 
```
Error 500 from Workspace Builder service for command "run": Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --mirror -- https://github.com/runwhen-contrib/rw-public-codecollection.git /tmp/tmp4mvc7a68/rw-public-codecollection
  stderr: 'Cloning into bare repository '/tmp/tmp4mvc7a68/rw-public-codecollection'...
fatal: unable to access 'https://github.com/runwhen-contrib/rw-public-codecollection.git/': Received HTTP code 403 from proxy after CONNECT
```


Add a config to the proxy to allow outbound connections and watch the logs: 
```
$ docker run --name squid-proxy --restart=always -d -p 3128:3128 --volume  /workspace/squid.conf:/etc/squid/squid.conf sameersbn/squid:3.5.27-2

 $ docker exec -it squid-proxy tail -f /var/log/squid/access.log


1708776990.033    481 172.17.0.1 TCP_TUNNEL/200 866205 CONNECT github.com:443 - HIER_DIRECT/20.29.134.23 -
1708776990.327    274 172.17.0.1 TCP_TUNNEL/200 4541 CONNECT github.com:443 - HIER_DIRECT/20.29.134.23 -
1708776991.052    567 172.17.0.1 TCP_TUNNEL/200 2602533 CONNECT github.com:443 - HIER_DIRECT/20.29.134.23 -
1708776991.367    281 172.17.0.1 TCP_TUNNEL/200 4933 CONNECT github.com:443 - HIER_DIRECT/20.29.134.23 -
1708777009.356    542 172.17.0.1 TCP_TUNNEL/200 1612419 CONNECT github.com:443 - HIER_DIRECT/20.29.134.23 -
1708777009.787    328 172.17.0.1 TCP_TUNNEL/200 4594 CONNECT api.github.com:443 - HIER_DIRECT/20.29.134.17 -
1708777009.872    242 172.17.0.1 TCP_TUNNEL/200 4827 CONNECT api.github.com:443 - HIER_DIRECT/20.29.134.17 -
1708777009.873     83 172.17.0.1 TCP_TUNNEL/200 20018 CONNECT avatars.githubusercontent.com:443 - HIER_DIRECT/185.199.109.133 -
1708777010.231    337 172.17.0.1 TCP_TUNNEL/200 4689 CONNECT api.github.com:443 - HIER_DIRECT/20.29.134.17 -
1708777010.331    242 172.17.0.1 TCP_TUNNEL/200 4911 CONNECT api.github.com:443 - HIER_DIRECT/20.29.134.17 -
1708777010.333     99 172.17.0.1 TCP_TUNNEL/200 352223 CONNECT avatars.githubusercontent.com:443 - HIER_DIRECT/185.199.109.133 -
1708777010.700    335 172.17.0.1 TCP_TUNNEL/200 4590 CONNECT api.github.com:443 - HIER_DIRECT/20.29.134.17 -
1708777010.795    253 172.17.0.1 TCP_TUNNEL/200 4949 CONNECT api.github.com:443 - HIER_DIRECT/20.29.134.17 -
1708777010.797     94 172.17.0.1 TCP_TUNNEL/200 159589 CONNECT avatars.githubusercontent.com:443 - HIER_DIRECT/185.199.109.133 -
1708777011.942    354 172.17.0.1 TCP_TUNNEL/200 6655 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.231    102 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.241     93 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.282    132 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.284    130 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.284    125 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.284    121 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.285    126 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.290    136 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.292    128 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.308     85 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.323    121 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.346     98 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.435     74 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.438     72 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.443     77 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.475    105 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.476    105 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.483    105 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.487    113 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.488    108 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.523    146 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.523    139 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.524    141 172.17.0.1 TCP_TUNNEL/200 6653 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.636    185 172.17.0.1 TCP_TUNNEL/200 6696 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -
1708777012.822    191 172.17.0.1 TCP_TUNNEL/200 6511 CONNECT raw.githubusercontent.com:443 - HIER_DIRECT/185.199.108.133 -

```

**Comment by zohebshaik41** [comment]
Here are the changes I did in runwhen-local deployment

Image: ghcr.io/runwhen-contrib/runwhen-local:0.5.2

```
    spec:
      containers:
      - env:
        - name: AUTORUN_WORKSPACE_BUILDER_INTERVAL
          value: "1800"
        - name: RW_LOCAL_TERMINAL_DISABLED
          value: "true"
        - name: HTTP_PROXY
          value: our-proxy-server-ip:8080
        - name: http_proxy
          value: our-proxy-server-ip:8080
        - name: https_proxy
          value: our-proxy-server-ip:8080
        - name: no_proxy
          value: 192.168.0.0/16,127.0.0.1,localhost,10.0.0.0/8,.svc,.cluster.svc,.svc.cluster.local,runwhen-local.runwhen-local.svc.cluster.local
        - name: HTTPS_PROXY
          value: our-proxy-server-ip:8080
        - name: NO_PROXY
          value: 192.168.0.0/16,.svc,.cluster.svc,.svc.cluster.local,runwhen-local.runwhen-local.svc.cluster.local,127.0.0.1,localhost,10.0.0.0/8
```
