### ISSUE TITLE
[runwhen-local-feedback] SLX names include "|"

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/runwhen-local#451]
**Observation** 
SLX names are showing up with "|" in the names which is breaking the upload feature into RunWhen Platform

Example: 
```
apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: b-rw-watcher--hlmrlss|hltlkflxc-bs-plt-flux-helm1
  labels:
    slx: b-rw-watcher--hlmrlss|hltlkflxc-bs-plt-flux-helm1
    workspace: b-rw-watcher
  annotations:
    fullSlxName: helmreleases|helm.toolkit.fluxcd.io|v2beta1|papi-session-cache-backend-services-platform-flux-helm

```

**Possible Suggestions**
Establish some characters that cannot be used in the slx name generation or shortening. 

**Any other details or context**
This feels like it was introduced in the past couple of releases.
